In [2]:
import os


aicrowd_challenge_name = "mabe-2022-mouse-triplets-video-data"
if not os.path.exists('data'):
    os.mkdir('data')
datafolder = 'data/'

## If data is already downloaded and stored on google drive, skip the download and point to the prepared directory
# datafolder = '/content/drive/MyDrive/mabe-2022-mouse-video/data/'

video_folder = f'{datafolder}video_clips/'

## user_train.npy

In [19]:
import os
import numpy as np
datafolder = './data/ants/'
keypoints = np.load(os.path.join(datafolder, 'user_train.npy'), allow_pickle=True).item()

In [20]:
keypoints.keys()

dict_keys(['vocabulary', 'sequences'])

In [21]:
vocabulary = keypoints['vocabulary']
vocabulary

['reapplied', 'grooming_self', 'exploring_object']

In [22]:
sequences = keypoints['sequences']
sequences.keys()
len(sequences.keys())

1948

In [28]:
import numpy as np

sequence_names = sequences.keys()
sequence_names = list(sequence_names)
task = [0] * 3
num_zeros = 0
num_ones = 0
for name in sequence_names:
    sequence = sequences[name]
    annotations = sequence['annotations']
    
    for i in range(len(annotations)):
        num_zeros += (annotations[i] == 0).sum()
        num_ones += (annotations[i] == 1).sum()

        # print(np.isnan(annotations[i]))
#         for j in range(len(annotations[i])):
#             if np.isnan(annotations[i][j]):
#                 task[i] += 1
print(len(sequence_names), len(sequence_names) * 900)
# print(task)
print(num_zeros, num_ones)
print(num_zeros + num_ones)

3


AssertionError: 

In [5]:
sequence_names = sequences.keys()
sequence_names = list(sequence_names)
task = [0] * 3
for name in sequence_names:
    sequence = sequences[name]
    annotations = sequence['annotations']
    for i in range(len(annotations)):
        for j in range(len(annotations[i])):
            if np.isnan(annotations[i][j]):
                task[i] += 1
print(len(sequence_names) * 900)
print(task)

1753200
[0, 1661400, 1661400]


In [17]:
sequence_names = sequences.keys()
sequence_names = list(sequence_names)
task = [0] * 3
for name in sequence_names:
    sequence = sequences[name]
    annotations = sequence['annotations']
    print(annotations.shape)
    assert 1==0

(2, 1800)


AssertionError: 

In [16]:
sequence_names = sequences.keys()
sequence_names = list(sequence_names)
for name in sequence_names:
    sequence = sequences[name]
    annotations = sequence['annotations']
    if not np.isnan(annotations[2][0]):
        print(annotations[2])
    

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [14]:
sequence_names = sequences.keys()
sequence_names = list(sequence_names)
clip_level = 0
frame_level = 0
for name in sequence_names:
    sequence = sequences[name]
    annotations = sequence['annotations']
    for i in range(len(annotations)):
        if np.all(annotations[i] == min(annotations[i])):
            clip_level += 1
        else:
            frame_level += 1
print('clip_level:', clip_level)
print('frame_level:', frame_level)

clip_level: 2100
frame_level: 3744


In [15]:
with open('./code/meta_info/user_train.txt', 'w') as f:
    for s in sorted(sequences.keys()):
        f.write(s + '\n')

In [16]:
for k, v in sequences.items():
    print(v['annotations'].shape)
    break

(3, 900)


In [27]:
for k, v in sequences.items():
    print(v['keypoints'].shape)
    break

(900, 4)


In [17]:
for i in v['keypoints']:
    print([int(t) for t in i * 224])

[103, 74, 85, 123]
[102, 73, 85, 123]
[102, 73, 85, 123]
[103, 74, 85, 123]
[102, 73, 85, 123]
[101, 73, 84, 122]
[101, 73, 84, 122]
[100, 73, 84, 122]
[101, 73, 84, 122]
[101, 73, 84, 122]
[99, 72, 84, 121]
[99, 72, 83, 121]
[99, 72, 84, 121]
[101, 73, 84, 122]
[99, 72, 83, 121]
[99, 71, 83, 121]
[99, 71, 83, 121]
[99, 71, 83, 121]
[99, 71, 83, 121]
[99, 71, 83, 121]
[99, 71, 84, 121]
[99, 71, 84, 121]
[99, 71, 84, 121]
[99, 71, 84, 121]
[99, 71, 84, 121]
[99, 70, 84, 121]
[99, 70, 84, 121]
[99, 70, 84, 121]
[99, 71, 84, 122]
[100, 71, 84, 122]
[100, 71, 84, 122]
[100, 71, 84, 122]
[100, 71, 84, 122]
[100, 71, 84, 122]
[100, 70, 84, 122]
[99, 70, 84, 122]
[99, 70, 84, 122]
[99, 70, 84, 122]
[99, 70, 84, 122]
[100, 70, 84, 122]
[99, 70, 84, 122]
[100, 70, 84, 122]
[100, 70, 84, 122]
[100, 70, 84, 122]
[99, 69, 84, 122]
[99, 69, 84, 121]
[99, 69, 84, 122]
[99, 69, 84, 122]
[99, 69, 84, 122]
[99, 70, 84, 122]
[100, 70, 84, 122]
[100, 70, 84, 122]
[100, 70, 84, 122]
[100, 71, 84, 122]
[10

In [28]:
import os
import numpy as np
keypoints_submit = np.load(os.path.join('data', 'submission_keypoints.npy'), allow_pickle=True).item()
keypoints_train = np.load(os.path.join('data', 'user_train.npy'), allow_pickle=True).item()
keypoints = {**keypoints_submit['sequences'], **keypoints_train['sequences']}

In [29]:
submit_keys = list(keypoints_submit['sequences'].keys())
train_keys = list(keypoints_train['sequences'].keys())

In [7]:
import random
random.shuffle(submit_keys)
random.shuffle(train_keys)
len_submit, len_train = len(submit_keys), len(train_keys)
select_submit = submit_keys[:len_submit//4]
select_train = train_keys[:len_train//4]
select_all = select_submit + select_train

In [8]:
frame_number_map_train = {}
for idx, seq in enumerate(select_all):
    frame_number_map_train[seq] = (idx*900, (idx+1)*900)

In [9]:
len(list(frame_number_map_train.keys()))

2859

In [51]:
np.save('./data/frame_number_map_train.npy', frame_number_map_train, allow_pickle=True)

In [22]:
print(keypoints_submit.keys())
print(keypoitns_train.keys())
print(keypoints_train['sequences']['001a9aa693e2cfe120ed'].keys())

dict_keys(['sequences'])
dict_keys(['vocabulary', 'sequences'])
dict_keys(['keypoints', 'annotations'])


## frame_number_map

In [36]:
import numpy as np
import os
datafolder = './data'
frame_number_map = np.load(os.path.join(datafolder, 'frame_number_map.npy'), allow_pickle=True).item()
frame_number_map2 = np.load((os.path.join(datafolder,'ants/frame_number_map_inference.npy')), allow_pickle=True).item()

In [38]:
total = 0
for k, v in frame_number_map2.items():
    total += (v[1] - v[0])
    if v[1] - v[0] != 900:
        print(k, v[1] - v[0])
print('All', total)
print('Finished')

ee7d67579ebcc9c49e7e 294
All 8541294
Finished


## submission_keypoints

In [20]:
import os
import numpy as np
datafolder = './data'
keypoints = np.load(os.path.join(datafolder, 'submission_keypoints.npy'), allow_pickle=True).item()

In [23]:
sequences = keypoints['sequences']
sequence_names = sequences.keys()
sequence_names = [sequence_name for sequence_name in sequence_names]
print(f"Number of sequences: {len(sequence_names)}")

sequence0_keypoints = sequences[sequence_names[0]]['keypoints']

print(f"Keypoinys shape: {sequence0_keypoints.shape}")

sequence_keypoints = sequences['ee7d67579ebcc9c49e7e']['keypoints']

print(f"Keypoinys shape: {sequence_keypoints.shape}")

Number of sequences: 9491
Keypoinys shape: (900, 4)
Keypoinys shape: (294, 4)


In [15]:
def dist(x1, y1, x2, y2):
    return np.sqrt((x1-x2)**2 + (y1-y2)**2)

In [25]:
change1 = 0
non_change1 = 0
change2 = 0
non_change2 = 0
    
for sid in range(len(sequence_names)):
    keypoints = sequences[sequence_names[sid]]['keypoints']
    last_x_1, last_y_1, last_x_2, last_y_2 = keypoints[0]
    for (x1, y1, x2, y2) in keypoints:
        if dist(x1, y1, last_x_1, last_y_1) > 0.0000001:
            change1 += 1
        else:
            non_change1 += 1
            
        if dist(x2, y2, last_x_2, last_y_2) > 0.0000001:
            change2 += 1
        else:
            non_change2 += 1
            
        last_x_1, last_y_1, last_x_2, last_y_2 = x1, y1, x2, y2

print(f"change1 / non_change1 = {change1} / {non_change1}")
print(f"change2 / non_change2 = {change2} / {non_change2}")

change1 / non_change1 = 5840358 / 2700936
change2 / non_change2 = 4006900 / 4534394


## user train video

In [15]:
import os
videos = os.listdir('./data/userTrain_videos_resized_224')

with open('./code/meta_info/userTrain_videos_resized_224.txt', 'w') as f:
    for s in sorted(videos):
        f.write(s.replace('.avi', '') + '\n')

## frame_number_map

In [16]:
frame_number_map = np.load('./data/frame_number_map.npy', allow_pickle=True).item()
with open('./code/meta_info/frame_number_map.txt', 'w') as f:
    for s in sorted(frame_number_map.keys()):
        f.write(s.replace('.avi', '') + '\n')

In [ ]:
import json

with open('./code/meta_info/submission.json', 'r') as f:
    v = json.load(f)
print(v)

In [15]:
import torch
a = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(a.shape)

b = None

for i in range(a.shape[0]):
    if b is None:
        b = a[0].unsqueeze(0).repeat(5, 1)
        print('a[0]', a[0])
        print('b', b)
    else:
        b = torch.cat((b, a[i].unsqueeze(0).repeat(5, 1)), 0)

print(b)

torch.Size([3, 3])
a[0] tensor([1, 2, 3])
b tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6],
        [7, 8, 9],
        [7, 8, 9],
        [7, 8, 9],
        [7, 8, 9],
        [7, 8, 9]])


## 900 frames 1 feature

In [2]:
import numpy as np
feat_path = '/home/sunchao/Multi_Agent_Round_2/code/checkpoints/antbeetle_sparse_checkpoints/s03_submission_ant_simclr.npy'

features = np.load(feat_path, allow_pickle=True)

(8541900, 128)


In [15]:
print(features.shape)
interval = 900
for start_id in range(0, 8541900, interval):
    cur_feat = features[start_id: start_id + interval, :]
    pool_feat = cur_feat.max(axis=0)
    expend_feat = np.repeat(np.expand_dims(pool_feat, axis=0), interval, axis=0)
    features[start_id: start_id + interval] =  expend_feat
    if start_id % 180000 == 0:
        print('current start_id', start_id)
assert features.shape == (8541900, 128)
np.save('./extend_1_feat_submission.npy', features)
    

(8541900, 128)
current start_id 0
current start_id 180000
current start_id 360000
current start_id 540000
current start_id 720000
current start_id 900000
current start_id 1080000
current start_id 1260000
current start_id 1440000
current start_id 1620000
current start_id 1800000
current start_id 1980000
current start_id 2160000
current start_id 2340000
current start_id 2520000
current start_id 2700000
current start_id 2880000
current start_id 3060000
current start_id 3240000
current start_id 3420000
current start_id 3600000
current start_id 3780000
current start_id 3960000
current start_id 4140000
current start_id 4320000
current start_id 4500000
current start_id 4680000
current start_id 4860000
current start_id 5040000
current start_id 5220000
current start_id 5400000
current start_id 5580000
current start_id 5760000
current start_id 5940000
current start_id 6120000
current start_id 6300000
current start_id 6480000
current start_id 6660000
current start_id 6840000
current start_id 7020

[[0.86339381 0.65890316 0.24433036 0.80786758]
 [0.94986246 0.43824417 0.2374474  0.18553133]
 [0.68997912 0.23481024 0.51683666 0.83998387]
 [0.01157644 0.1780506  0.06051886 0.78909702]
 [0.87429636 0.5654838  0.22343273 0.94956774]]


array([0.94986246, 0.65890316, 0.51683666, 0.94956774])

## Moving label

In [27]:
import os
import numpy as np
datafolder = './data'
keypoints = np.load(os.path.join(datafolder, 'submission_keypoints.npy'), allow_pickle=True).item()

In [28]:
sequences = keypoints['sequences']
sequence_names = sequences.keys()
sequence_names = [sequence_name for sequence_name in sequence_names]
print(f"Number of sequences: {len(sequence_names)}")

sequence0_keypoints = sequences[sequence_names[0]]['keypoints']

print(f"Keypoinys shape: {sequence0_keypoints.shape}")

Number of sequences: 9491
Keypoinys shape: (900, 4)


In [29]:
def dist(x1, y1, x2, y2):
    return np.sqrt((x1-x2)**2 + (y1-y2)**2)

In [41]:
moving_label = {}

for sid in range(len(sequence_names)):
    label = []
    keypoints = sequences[sequence_names[sid]]['keypoints']
    last_x_1, last_y_1, last_x_2, last_y_2 = keypoints[0]
    for (x1, y1, x2, y2) in keypoints:
        state1, state2 = 0, 0 
        if dist(x1, y1, last_x_1, last_y_1) > 0.0000001:
            state1 = 1
        else:
            state1 = 0
            
        if dist(x2, y2, last_x_2, last_y_2) > 0.0000001:
            state2 = 1
        else:
            state2 = 0
            
        label.append([state1, state2])
    
    moving_label[sequence_names[sid]] = np.array(label)
    
    if sid % 1000 == 0:
        print(f"Processing {sid}")

np.save('./data/moving_labels.npy', moving_label, allow_pickle=True)

Processing 0
Processing 1000
Processing 2000
Processing 3000
Processing 4000
Processing 5000
Processing 6000
Processing 7000
Processing 8000
Processing 9000


In [34]:
import numpy as np
moving_labels = np.load(os.path.join('./data', "moving_labels.npy"), allow_pickle=True)

In [35]:
a = moving_labels.item()

In [38]:
b = a[list(a.keys())[0]]

In [39]:
b.shape

AttributeError: 'list' object has no attribute 'shape'

## frame crop 224

In [24]:
import os
dir_path = 'data/ants/frames_cropped_224'
video_list = os.listdir(dir_path)
dis_crop = []
frame_num_per_video = 900
for video_name in video_list:
    video_path = os.path.join(dir_path, video_name)
    num_imgs = len(os.listdir(video_path))
    if num_imgs != frame_num_per_video * 2:
        dis_crop.append(video_name)

In [25]:
print(dis_crop)

[]


## cluster feature map

In [19]:
import numpy as np
import os
datafolder = './data/ants'
frame_number_map = np.load(os.path.join(datafolder, 'frame_number_map_training.npy'), allow_pickle=True).item()

In [21]:
frame_number_map.keys()

dict_keys(['c7c30d36ec138b6b7502', '1a4cedf46edb6c88b82c', '2f469108bc5b372b6b99', '8b86da0fc2c35f9eb9b7', 'acb1a32681555bf6010d', '97a95705a41317bbf8de', '16a7a056a90a9a674eba', '619377ff7ab8b8ac5b0f', '781fa488804211bacee2', '8bb15f441e00f68a071c', 'a2e9b5b21b2635df86c7', '3f626343f22eea40825d', '13588887b7f73174a01d', '0e2cb35948a32a4f0901', 'df4ecebb0e41fbd9310e', '488f8fcdfa5531867bdc', 'daeda118a304dfda3031', 'c53301a7915d70abfc1c', 'ad0010798fe5f2b01fcd', '65f7e15ac7b863bf33a7', '73668c7ddcf8547bac7e', '13b7467a322497edfd05', '37c6d9d83d7137bfb6bf', '0622058f54256b9e401f', '7086f8440fe247fb8e6a', '6bbe78ae3ca59953bf15', '2689eb818688d85ad7ea', 'de95a6a57a9383d37b2d', '0cefe6834acb601ab565', '8878ca16da0c985f88fd', '727bea48823e2f977f2e', 'e205eb0aa800e6f7920b', 'c4aa15c1a5385d8b8e41', '1436fe47c6437fdabe98', '33648f03a5694c9564a4', '979865fb567cf8416ca9', '0a4072c2550bf85c0f5c', '4de28e75a3f383af4e6f', '80dc3760e34bfd5495e8', '09bed47ab46a07446878', '3b1f6a8e3034887a02d6', '441e